In [ ]:
import torch
torch.__version__

'2.2.1+cu121'

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
type(scalar.item())

int

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape

torch.Size([1, 3, 3])

In [ ]:
torch.tensor([[[7,4],[0,1]],[[7,4],[0,1]],[[7,4],[0,1]]]).shape

torch.Size([3, 2, 2])

In [ ]:
random_tensor = torch.rand(size =(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.4095, 0.8264, 0.8605, 0.3181],
         [0.7684, 0.0362, 0.4756, 0.5458],
         [0.8478, 0.8190, 0.9671, 0.5162]]),
 torch.float32)

In [ ]:
random_image_size_tensor = torch.rand(size = (224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size = (3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [ ]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [ ]:
#zero_to_ten_deprecated = torch.range(0,10)
zero_to_ten = torch.arange(0,11,1)
zero_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=None,device=None,requires_grad = False)
float_32_tensor.shape,float_32_tensor.dtype,float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
some_tensor = torch.rand(3,4)

print(some_tensor)
print(f'Shape of Tensor: {some_tensor.shape}')
print(f'Shape of Tensor: {some_tensor.dtype}')
print(f'Shape of Tensor: {some_tensor.device}')

tensor([[0.1959, 0.5900, 0.5613, 0.8123],
        [0.5920, 0.0533, 0.9387, 0.5877],
        [0.7150, 0.6542, 0.7068, 0.8487]])
Shape of Tensor: torch.Size([3, 4])
Shape of Tensor: torch.float32
Shape of Tensor: cpu


In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [ ]:
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [ ]:
torch.multiply(tensor,10)

tensor([10, 20, 30])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
print(tensor,'*',tensor)
print('Equals', tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
%%time
val = 0
for i in range(len(tensor)):
  val+=tensor[i]*tensor[i]
val

CPU times: user 1.6 ms, sys: 38 µs, total: 1.64 ms
Wall time: 3.05 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 1.05 ms, sys: 2 µs, total: 1.06 ms
Wall time: 1.07 ms


tensor(14)

In [ ]:
%%time
tensor @ tensor

CPU times: user 1.09 ms, sys: 0 ns, total: 1.09 ms
Wall time: 1.21 ms


tensor(14)

In [ ]:
#shape -> 3,2
tensor_a = torch.tensor([[1,2],[3,4],[5,6]],dtype = torch.float32)
#shape -> 3,2
tensor_b = torch.tensor([[7,10],[8,11],[9,12]],dtype=torch.float32)
torch.matmul(tensor_a,tensor_b.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
tensor_a

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
#3,2 * 2*6 = 3, 6
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=3,out_features = 6)
x = tensor_a.T
output = linear(x)
print(x.shape)
print(output.shape)

torch.Size([2, 3])
torch.Size([2, 6])


In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.min()

tensor(0)

In [ ]:
x[x.argmax()]

tensor(90)

In [ ]:
tensor = torch.arange(10.,100.,10)
tensor.dtype

torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [ ]:
x = torch.arange(1.,8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
x_reshaped = x.reshape(1,7)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
z = x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [ ]:
print(x_reshaped.shape)
x_squeezed = x_reshaped.squeeze()
print(x_squeezed.shape)
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(x_unsqueezed.shape)

torch.Size([1, 7])
torch.Size([7])
torch.Size([1, 7])


In [ ]:
x_orig = torch.rand(size=(224,224,3))
x_permute = x_orig.permute(2,0,1)
print(x_permute.shape)

torch.Size([3, 224, 224])


In [ ]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
x[:,1,1]

tensor([5])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(1.0,8.0)
tensor = torch.from_numpy(arr)
arr,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
arr = arr + 1
arr,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))